version: '3.8'
services:
  authentication-service:
    build: ./authentication-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
  reservation-service:
    build: ./reservation-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
  flight-service:
    build: ./flight-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql
  user-service:
    build: ./user-service
    ports:
      - "8085:8085"
    depends_on:
      - mysql
  payment-service:
    build: ./payment-service
    ports:
      - "8086:8086"
    depends_on:
      - mysql
  dashboard-service:
    build: ./dashboard-service
    ports:
      - "8087:8087"
    depends_on:
      - mysql
  airline-service:
    build: ./airline-service
    ports:
      - "8088:8088"
    depends_on:
      - mysql
  airport-service:
    build: ./airport-service
    ports:
      - "8089:8089"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: