version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: volmaghreb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: volmaghreb_db
      MYSQL_USER: volmaghreb
      MYSQL_PASSWORD: volmaghreb123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - volmaghreb-network

  adminer:
    image: adminer
    container_name: volmaghreb-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - volmaghreb-network
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  volmaghreb-network:
    driver: bridge
