services:
  - type: web
    name: volmaghreb-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: # Set this in Render dashboard - your Aiven MySQL URL
      - key: DB_USERNAME
        value: # Set this in Render dashboard - your Aiven username
      - key: DB_PASSWORD
        value: # Set this in Render dashboard - your Aiven password
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
